name: Publish to NuGet
on:
  workflow_dispatch:
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Publish to NuGet
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          # Config: https://github.com/brandedoutcast/publish-nuget
          PROJECT_FILE_PATH: Nekos.Net/Nekos.Net.csproj
          PACKAGE_NAME: Nekos.Net
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: false