name: Publish to NuGet
on:
  workflow_dispatch:
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Move the package file
        run: |
          cd /home/runner/work/Nekos.Net/Nekos.Net/Nekos.Net/bin/Release/
          mv Nekos.Net.* ../../../
      - name: Publish to NuGet
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Nekos.Net/Nekos.Net.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}