name: Publish to NuGet
on:
  workflow_dispatch:
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Move the package file
        run: |
          dotnet build Nekos.Net -c Release
          dotnet pack Nekos.Net -c Release
          cd ./Nekos.Net/bin/Release/
          mv Nekos.Net.*.nupkg Nekos.Net.nupkg
          dotnet nuget push Nekos.Net.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json